GET http://localhost:3001/api/ping

###
GET http://localhost:3001/api/diagnoses

###
GET http://localhost:3001/api/patients

###
POST http://localhost:3001/api/patients
Content-Type: application/json

{
    "name" : "utku",
    "dateOfBirth" : "1986-07-09",
    "gender" : "other",
    "occupation" : "Trabzon",
    "ssn" : "35235313"
}

###
GET http://localhost:3001/api/patients/d27736ec-f723-11e9-8f0b-362b9e155667

###
POST http://localhost:3001/api/patients/d27736ec-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
    "date": "2019-10-20",
    "specialist": "MD House",
    "type": "HealthCheck",
    "description": "Yearly control visit. Cholesterol levels back to normal.",
    "healthCheckRating": 0,
    "diagnosisCodes" : ["L60.1"]
}