GET http://localhost:3001/api/ping

###
GET http://localhost:3001/api/diagnoses

###
GET http://localhost:3001/api/patients

###
POST http://localhost:3001/api/patients
Content-Type: application/json

{
    "name" : "utku",
    "dateOfBirth" : "1986-07-09",
    "gender" : "male",
    "occupation" : "Trabzon",
    "ssn" : "35235313"
}